export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_CLEAR_ERROR = "AUTH_CLEAR_ERROR";
export const ACCOUNTS_REQUEST = "ACCOUNTS_REQUEST";
export const ACCOUNTS_SUCCESS = "ACCOUNTS_SUCCESS";
export const ACCOUNTS_FAILURE = "ACCOUNTS_FAILURE";

export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
export const CATEGORIES_FAILURE = "CATEGORIES_FAILURE";
